### ISSUE TITLE
solar tweaks wont launch 1.8 but it launches other versions

### ISSUE THREAD

**Issue by noahbt7871** [Solar-Tweaks/SolarPatcher#16]
solar tweaks wont launch 1.8 but it launches other versions

**To Reproduce**
-launch 1.8

**Expected behavior**
game should launch

**Screenshots**

**Environment (please complete the following information):**
 OS arch linux with KDE

**Additional context**
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
    at java.base/java.lang.reflect.Method.invoke(Method.java:577)
    at com.moonsworth.lunar.patcher.LunarMain.main(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: /home/noah/.lunarclient/offline/1.8/natives/liblwjgl64.so: /usr/lib/jvm/java-18-jdk/lib/libjawt.so: version `SUNWprivate_1.1' not found (required by /home/noah/.lunarclient/offline/1.8/natives/liblwjgl64.so)
    at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
    at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:395)
    at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:234)
    at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:176)
    at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:322)
    at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:291)
    at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2427)
    at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
    at java.base/java.lang.System.loadLibrary(System.java:2015)
    at org.lwjgl.Sys$1.run(Sys.java:72)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
    at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
    at org.lwjgl.Sys.loadLibrary(Sys.java:87)
    at org.lwjgl.Sys.<clinit>(Sys.java:117)
    at net.minecraft.v1_8.hpehhpasahpehpeeahapahapp.hasahhsaahhhsspehpessesas(SourceFile:2539)
    at net.minecraft.client.main.Main.main(SourceFile:41)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    ... 2 more

**Comment by 770grappenmaker** [comment]
This happens with the specified jre isn't java 16 or higher
